name: Build Spring Boot Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Build project with Maven
      run: 
          mvn -B clean package     

    - name: Run tests
      run: mvn test

    - name: Run STA Dependency-Check
      run: mvn org.owasp:dependency-check-maven:check
       
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run OWASP ZAP DAST
      run: |
        docker run --name zap-container -u zap -p 9090:9090 -d owasp/zap2docker-stable
        mvn -Dzap.host=172.17.0.1 -Dzap.port=9090 verify
